### ISSUE TITLE
coil addresses larger than 2000?

### ISSUE THREAD

**Issue by egradman** [ryanww/ofxModbusTCP#1]
Hi, I'm using a CLICK Koyo PLC that supports modbus.  I have python code using pyModbusTCP that's successfully exercising the device, and I'm trying to port this code to work with your module.  However, I'm getting errors that the coil address (8192) is too large (larger than 2000, as I found in your code).  Merely changing that constant in your addon creates new errors.

I'm not familiar enough with the modbus protocol to know how to fix this issue.  Here's my working python code 

```
#!/usr/bin/env python3

from pyModbusTCP.client import ModbusClient
import time

SERVER_HOST = "192.168.0.200"
SERVER_PORT = 502

c = ModbusClient()

c.host(SERVER_HOST)
c.port(SERVER_PORT)

toggle = True

while True:
    # open or reconnect TCP to server
    if not c.is_open():
        if not c.open():
            print("unable to connect to "+SERVER_HOST+":"+str(SERVER_PORT))

   # if open() is ok, write coils (modbus function 0x01)
    if c.is_open():
        for addr in range(8192,8198):
            is_ok = c.write_single_coil(addr, toggle)
            if is_ok:
                print("bit #" + str(addr) + ": write to " + str(toggle))
            else:
                print("bit #" + str(addr) + ": unable to write " + str(toggle))
            time.sleep(.1)

        time.sleep(1)

    toggle = not toggle
    # sleep 2s before next polling
    time.sleep(1)
```

**Comment by ryanww** [comment]
Hello - Yeah I originally had those much smaller as I never needed that many. I've actually modified that and in the most recent version - you can set the number of them. Look at the .cpp file in the first few lines. Right now they are set to take 5000 coils and registers.

Currently I'm trying to fix a couple things and implement function 15 & 16, so it might change. But should be back to up and running by the end of today or tomorrow.
